# Generated by Django 5.2.1 on 2025-08-19 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_uploaded_at_document_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Write_permissions',
            field=models.ManyToManyField(blank=True, related_name='documents_can_write', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='read_permissions',
            field=models.ManyToManyField(blank=True, related_name='documents_can_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
