# Generated by Django 5.2.1 on 2025-08-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_write_permissions_document_read_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='Write_permissions',
            new_name='write_permissions',
        ),
    ]
